### ISSUE TITLE
npm install issue - gyp ERR

### ISSUE THREAD

**Issue by ddevice1234** [mschwarzmueller/angular-2-beta-boilerplate#12]
Seeing these errors when I execute the install command:

> bufferutil@1.2.1 install C:\Users\test\Documents\Angular2 Training\node_modules\bufferutil
> node-gyp rebuild

C:\Users\test\Documents\Angular2 Training\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\test\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\test\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\test\Documents\Angular2 Training\node_modules\bufferutil
gyp ERR! node -v v5.9.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install C:\Users\test\Documents\Angular2 Training\node_modules\utf-8-validate
> node-gyp rebuild

C:\Users\test\Documents\Angular2 Training\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\test\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\test\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\test\Documents\Angular2 Training\node_modules\utf-8-validate
gyp ERR! node -v v5.9.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1

Did I need to install Python to make this install work?  (I'm on Win 7)

**Comment by mschwarzmueller** [comment]
Hi,
these errors are not necessarily a problem. Does the overall installation finish without an error? Because I get the same errors but the project will run fine nonetheless.

**Comment by ddevice1234** [comment]
Mostly :-)

1) npm start seems to work fine, as it brings up the Hello World page in Chrome for me.

2) But when I try "gulp" command in a new Win7 command window, as directed, I get:
C:\Users\test\Documents\Angular2 Training>gulp
'gulp' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mschwarzmueller** [comment]
You don't need to run gulp separately. It is automatically started when you run 'npm start'.
If you still want to run it manually you should 'npm install -g gulp'. But again: This is not required

**Comment by ddevice1234** [comment]
Thanks for being so quick in your reply. 

Also, you have a compelling teaching style!

**Comment by mschwarzmueller** [comment]
Great to hear you're liking it :)

**Comment by minhth1905** [comment]
Dear Maximilian,
You can help me about:
when I build project "Hello world" by "npm start" in terminal, I have a
error "this site can't be rearched " same the picture I attach.
Thanks you,

2016-03-18 15:36 GMT+07:00 Maximilian <notifications@github.com>:

> Great to hear you're liking it :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mschwarzmueller/angular-2-beta-boilerplate/issues/12#issuecomment-198256206>
>



-- 
================================

    Tran Huu Minh, Mr
    Imformation Technology,
    University of Engineering and Technology
    Vietnam National University, Hanoi
    [Phone : +84-984806847]
    [Email: minhth1905@gmail.com]

=================================

**Comment by mschwarzmueller** [comment]
Hi, unfortunately I can't see any picture here. Can you post the error log?

**Comment by dilipsingh0506** [comment]
npm ERR! shasum check failed for C:\Users\XXXXX\AppData\Local\Temp\npm-8600-a03c611b\registry.npmjs.org\angular2\-\angular2-2.0.0-beta.14.t
gz
npm ERR! Expected: 86d3e195ec1e5069168c14bc60a7dcab56b7dfdf
npm ERR! Actual:   bc442d5ecee4f08faed5465137409d24062b9a1b
npm ERR! From:     https://registry.npmjs.org/angular2/-/angular2-2.0.0-beta.14.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by dilipsingh0506** [comment]
Please help with this issue. I have taken your boiler plate & tried to create sample project through it
