### ISSUE TITLE
REST HTTP

### ISSUE THREAD

**Issue by oussoumab** [mschwarzmueller/angular-2-beta-boilerplate#19]
I can't post a rest Web service
I followed this video "Angular 2 Tutorial (2016) - HTTP (GET and POST to RESTful Service)"
but I get an error message
Can you please help me
![capture du 2016-04-01 09 29 59](https://cloud.githubusercontent.com/assets/17901577/14241881/15568e60-fa46-11e5-86c9-c19912706188.png)
![capture du 2016-04-01 09 30 32](https://cloud.githubusercontent.com/assets/17901577/14241882/155df8e4-fa46-11e5-9936-fec92f6a9f39.png)
![capture du 2016-04-01 09 31 31](https://cloud.githubusercontent.com/assets/17901577/14241884/1562defe-fa46-11e5-9363-10391035aa77.png)
![capture du 2016-04-01 09 32 09](https://cloud.githubusercontent.com/assets/17901577/14241883/1560e50e-fa46-11e5-9ef9-27067f3a0a3b.png)

**Comment by mschwarzmueller** [comment]
This has nothing to do with this repo, please post it in the video comments.
