### ISSUE TITLE
Something about architecture

### ISSUE THREAD

**Issue by jtouzy** [mschwarzmueller/angular-2-beta-boilerplate#4]
Hi,

This is not a real problem in the app but just a problem I see with Angular 2.

Angular2 create templates in the DOM with attributes for recognize them, like "ng-content-r4nd0m" for one template, and in case we use another one inside this first template, the attribute is changed for all this second template. Fine, that's ok.
In case we have components styled, (with styleUrls), Angular generates styles with this name.
Le'ts get an example :

My template is like this in the DOM:
`<div class="my-class-on-element" ng-content-kb2678></div>`
The styles created are:
`.my-class-on-element[ng-content-kb2678] { background-color: red; }`

But, I have a question with that. If i want to make a component library, with styled components, how the users can modify my styled components ? There is no way that their classes can override the component CSS classes.

For example:
`.my-class-on-element { background-color: green; }`
Will not be applied because of the components mechanism. This is a good thing in all the general cases, for separate all components styles, but in the case I described before I think this could be a problem.

What do you think about that ?

(PS: Sorry for my frenglish)

**Comment by mschwarzmueller** [comment]
Hi,
that is an interesting point you bring up there. I think the only way to overwrite is, to actually edit the stylesheet or the in-file styles ('styles: []' metadata). But I recognize that this kind of is against the idea of a component library.
It might work to overwrite styles using '!important' statement I think. But that would obviously require the user to annotate every style with '!important'.
The general problem you describe is certainly creating some difficulties in the described usecase.

**Comment by jtouzy** [comment]
I see few days ago that ng-bootstrap already made their components library (beta) in Angular2 (called ng2-bootstrap). Don't think they have this problem because they don't use styles directly integrated to their components... So we just need to override bootstrap styles. 
Don't really solve the problem but just for information...

**Comment by mschwarzmueller** [comment]
Hi, sorry to reply this late.
Thanks for sharing this, although - as you say - it's not really solving this problem. But probably that is the only way to handle it right now.
