### ISSUE TITLE
The selector "my-app" did not match any elements

### ISSUE THREAD

**Issue by ndnguru** [mschwarzmueller/angular-2-beta-boilerplate#5]
I noticed while running this boilerplate that Angular sometimes complains about the my-app selector not being found.

Potential fix:
I believe the systemjs script that starts up the app should be placed after the <my-app> tags. This will ensure that once Angular is bootstrapped, the DOM already has loaded the <my-app> element.  Once I did this, my problem subsided.

index.html should look like this:
```
<body>
<my-app>Loading...</my-app>

<script>
    System.config({
        packages: {
            app: {
                format: 'register',
                defaultExtension: 'js'
            }
        }
    });
    System.import('app/boot')
            .then(null, console.error.bind(console));
</script>
</body>
```

thoughts?

**Comment by mschwarzmueller** [comment]
Sounds reasonable to me - only thing which I find a bit strange is, that with this boilerplate I follow the quickstart guide form angular.io where they place Systemjs BEFORE <my-app></my-app>.
But your explanation makes sense, I'll update it to reflect this.
