### ISSUE TITLE
Npm Warn.. TSD Depreceated..

### ISSUE THREAD

**Issue by amanuel2** [mschwarzmueller/angular-2-beta-boilerplate#8]
TSD Is depreciated... Can you guys try changing from tsd? Thankyou

**Comment by mschwarzmueller** [comment]
Hi, I will try to change it soon but since I use this boilerplate in an Angular 2 course I have to be careful not breaking anything. Currently tsd is required for zonejs (at least the version used here) otherwise installation would fail.
